name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp:
          - 24
          - 25
          - 26
          - 27
        rebar3:
          - 3.23.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1.18.2
        with:
          otp-version: ${{ matrix.otp }}
          rebar3-version: ${{ matrix.rebar3 }}
      - name: Ensure version consistency
        run: ./check_vsns.escript
      - name: Compile and test
        run: make
      - name: Archive CT Logs
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: ct-logs-${{ matrix.otp }}
          path: _build/test/
          retention-days: 1
