name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['23.2', '24.0']
        rebar3: ['3.14.1', '3.14.3']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - name: Ensure version consistency
        run: ./check_vsns.escript
      - name: Compile and test
        run: make
      - name: Archive CT Logs
        uses: actions/upload-artifact@v2
        with:
          name: ct-logs
          path: _build/test/
          retention-days: 1
